name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: fastify_api_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d fastify_api_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    env:
      NODE_ENV: test
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: fastify_api_test
      DB_USER: postgres
      DB_PASSWORD: 123456
      JWT_SECRET: chave_secreta_teste
      DB_SSL: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Initialize test database
        run: psql -h localhost -U $DB_USER -d $DB_NAME -f database/init/01-create-usuarios.sql
        env:
          PGPASSWORD: ${{ env.DB_PASSWORD }}

      - name: Run tests
        run: npm test

  deploy-aws:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::952846578181:role/GitHubActionsFastifyApiDeployRole
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
